server:
  port: 8761
spring:
  application:
    name: server-register-eureka
eureka:
  instance:
    preferIpAddress: true
  client:
    # 自己不注册到自己的服务商
    register-with-eureka: false
    # 不拉取服务列表信息
    fetch-registry: false
  server:
    # 关闭自我保护模式
    enable-self-preservation: false
    # 定期清理无效连接
    eviction-interval-timer-in-ms: 10000
