server:
  port: 8761
spring:
  application:
    name: server-register-eureka
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
  instance:
    preferIpAddress: true
    instance-id: ${spring.cloud.client.ipAddress}:${spring.application.instance_id:${server.port}}
    appname: ${spring.application.name}
  server:
    enable-self-preservation: false
